# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/my-first-blog"

# ç½‘é¡µçš„æ ‡é¢˜
title: "ç§‘æŠ€é‡è§å¥¹"
# ç½‘ç«™çš„ä¸»æ ‡é¢˜
name: "æˆ‘è¦å®Œæˆä¸€å°æ—¶ç¼–ç¨‹æŒ‘æˆ˜ ğŸ¥³"
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "è¿™æ˜¯æˆ‘çš„å°ä¸–ç•Œï¼Œç”¨äºè®°å½•ç”Ÿæ´»ï¼Œå·¥ä½œ"

aboutme: "æˆ‘çš„ç”Ÿæ´»ï¼Œå·¥ä½œ ğŸ˜‰ğŸ•ğŸ§"

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
